### ISSUE TITLE
 The question about Observation Probability Function

### ISSUE THREAD

**Issue by Louis-Quan** [Future-Power-Networks/MAPDN#17]
Dear author:
    Thank you very much for providing the code for the public. I have two question after reading your article and code. 
    First, the definition of observation probability function is the probability of joint observations. I don't understand why you define the observation probability function as the measurement errors that may occur in sensors.
    Second, In the section 4.1 of your article you said "Specifically, Ω(ot+1|st+1, at) = st+1 + N (0, Σ), where N (0, Σ) is an isotropic multi-variable Gaussian distribution and Σ is dependent on the physical properties of sensors" However, I can‘t find the observation probability function in your code. 
    I'll appreciate it if you could answer my question. Thank you so much!!!
Best wishes

**Comment by hsvgbkhgbv** [comment]
Dear Quan,

Thank you for your interests. 

Q1. First, the definition of observation probability function is the probability of joint observations. I don't understand why you define the observation probability function as the measurement errors that may occur in sensors.

A1. This is the common setting to instantiate or model the observation probability function in the realistic world. Please refer to [1]. 

Q2. Second, In the section 4.1 of your article you said "Specifically, Ω(ot+1|st+1, at) = st+1 + N (0, Σ), where N (0, Σ) is an isotropic multi-variable Gaussian distribution and Σ is dependent on the physical properties of sensors" However, I can‘t find the observation probability function in your code.

A2. See https://github.com/Future-Power-Networks/MAPDN/blob/fd90eebe74fe7d7e9f33cd92afeb4f444cde031d/environments/var_voltage_control/voltage_control_env.py#L65-L69


Reference
[1] Oliehoek, F. A., & Amato, C. (2016). A concise introduction to decentralized POMDPs. Springer.

**Comment by Louis-Quan** [comment]
Thank you for your reply. It's really kind of you. But I still can't understand the code you show. It is just a caculation of standard deviation. What is the isotropic multi-variable Gaussian distribution and Σ(dependent on the physical properties of sensors)?
In your code you have defined a function "def _set_demand_and_pv(self, add_noise=True):", which add uncertainty to data with unit truncated gaussian. Is it the observation probability function? Or is it the " In practice, Gaussian noises are added to load active and reactive powers" in your paper?

I'm looking forward to your reply. Thank you so much!

**Comment by hsvgbkhgbv** [comment]
Dear Quan,

Q1. But I still can't understand the code you show. It is just a caculation of standard deviation. What is the isotropic multi-variable Gaussian distribution and Σ(dependent on the physical properties of sensors)?
In your code you have defined a function "def _set_demand_and_pv(self, add_noise=True):", which add uncertainty to data with unit truncated gaussian. Is it the observation probability function?

A1. Sorry for my carelessness due to the emergent rebuttals. The snippet of code I showed before was just the definition of std and you are right that the   "def _set_demand_and_pv(self, add_noise=True)" is the function to add noise with the std defined above.

Q2. Or is it the " In practice, Gaussian noises are added to load active and reactive powers" in your paper?

A2. Yes, it is. Besides, the uncertainty of the sensor for PV active power is also considered such that
https://github.com/Future-Power-Networks/MAPDN/blob/fd90eebe74fe7d7e9f33cd92afeb4f444cde031d/environments/var_voltage_control/voltage_control_env.py#L491-L492

**Comment by Louis-Quan** [comment]
Thank you very much！Respect！

**Comment by hsvgbkhgbv** [comment]
You are welcome.
